In [27]:

import pandas as pd

df = pd.read_csv("Nubank_2026-06-11 (1).csv",encoding='utf-8',sep=',')


df.rename(columns={'title':'Despesa','amount':'Valor','date':'Data'},inplace=True)

df['Tipo de Pagamento'] = 'Cartão de Crédito NUBANK'
df['Tipo de Despesa'] = ''

df['Pagamento'] = 'Á Vista'

In [42]:
teste = 'ola'
teste.startswith('o')
teste.count("l")
teste.find("u")

-1

In [28]:
df

,Data,Despesa,Valor,Tipo de Pagamento,Tipo de Despesa,Pagamento
0,2026-06-03,Multsom,"97,50",Cartão de Crédito NUBANK,,Á Vista
1,2026-06-02,Comfrutas Laranja Doce,"65,62",Cartão de Crédito NUBANK,,Á Vista
2,2026-05-28,Ips Br*Onlyfans,"26,12",Cartão de Crédito NUBANK,,Á Vista
3,2026-05-27,Chies Barber,"70,00",Cartão de Crédito NUBANK,,Á Vista
4,2026-05-27,Ebn*Capcut,"13,00",Cartão de Crédito NUBANK,,Á Vista
5,2026-05-26,Amigao Cianorte I,"60,07",Cartão de Crédito NUBANK,,Á Vista
6,2026-05-25,IOF de volta de Lovable,"- 0,99",Cartão de Crédito NUBANK,,Á Vista
7,2026-05-25,Lovable,"28,33",Cartão de Crédito NUBANK,,Á Vista
8,2026-05-25,"IOF de ""Lovable""","0,99",Cartão de Crédito NUBANK,,Á Vista
9,2026-05-25,Dl*Google Moises,"9,99",Cartão de Crédito NUBANK,,Á Vista
10,2026-05-23,Ips,"134,27",Cartão de Crédito NUBANK,,Á Vista
11,2026-05-23,Ips Br*Onlyfans,"52,61",Cartão de Crédito NUBANK,,Á Vista
12,2026-05-23,Amazon Br *Amazon,"41,26",Cartão de Crédito NUBANK,,Á Vista
13,2026-05-22,Claude.Ai Subscription,"113,35",Cartão de Crédito NUBANK,,Á Vista
14,2026-05-22,"IOF de ""Claude.Ai Subscription""","3,96",Cartão de Crédito NUBANK,,Á Vista
15,2026-05-21,IOF de volta de Claude.Ai Subscription,"- 3,96",Cartão de Crédito NUBANK,,Á Vista
16,2026-05-20,Jim.Com* Gabriel Fran,"1.800,00",Cartão de Crédito NUBANK,,Á Vista
17,2026-05-16,"IOF de ""Railway""","0,91",Cartão de Crédito NUBANK,,Á Vista
18,2026-05-16,Comfrutas Laranja Doce,"144,42",Cartão de Crédito NUBANK,,Á Vista
19,2026-05-16,Hk Clinic,"300,00",Cartão de Crédito NUBANK,,Á Vista
20,2026-05-16,Dl*Google Google,"12,50",Cartão de Crédito NUBANK,,Á Vista
21,2026-05-16,Railway,"26,21",Cartão de Crédito NUBANK,,Á Vista
22,2026-05-15,IOF de volta de Railway,"- 0,91",Cartão de Crédito NUBANK,,Á Vista
23,2026-05-14,Mp *Gfarma,"127,42",Cartão de Crédito NUBANK,,Á Vista
24,2026-05-14,QMS,"35,50",Cartão de Crédito NUBANK,,Á Vista
25,2026-05-14,Ips Br*Onlyfans,"17,80",Cartão de Crédito NUBANK,,Á Vista
26,2026-05-12,IOF por fatura atrasada,"7,36",Cartão de Crédito NUBANK,,Á Vista
27,2026-05-12,Multa por fatura atrasada,"37,93",Cartão de Crédito NUBANK,,Á Vista
28,2026-05-12,Juros de atraso do Pix no crédito para QMS INT...,"0,03",Cartão de Crédito NUBANK,,Á Vista
29,2026-05-12,Multa de atraso do Pix no crédito para QMS INT...,"0,39",Cartão de Crédito NUBANK,,Á Vista
30,2026-05-12,IOF de atraso do Pix no crédito para QMS INTER...,"0,00",Cartão de Crédito NUBANK,,Á Vista
31,2026-05-12,Pagamento recebido,"- 1.908,86",Cartão de Crédito NUBANK,,Á Vista
32,2026-05-11,Pix no Crédito - QMS INTERNACIONAL PROGRAMACAO...,"21,46",Cartão de Crédito NUBANK,,Á Vista
33,2026-05-11,Pix no Crédito - S A RECEBIMENTOS LTDA,"2,70",Cartão de Crédito NUBANK,,Á Vista
34,2026-05-11,Valor pendente do mês anterior,"1.889,36",Cartão de Crédito NUBANK,,Á Vista
35,2026-05-11,Pix no Crédito - QMS INTERNACIONAL PROGRAMACAO...,"22,74",Cartão de Crédito NUBANK,,Á Vista
36,2026-05-08,Hk Clinic,"300,00",Cartão de Crédito NUBANK,,Á Vista
37,2026-05-05,Panobiancos Academia -,"109,90",Cartão de Crédito NUBANK,,Á Vista
38,2026-05-04,Aprova Total - Parcela 4/12,"83,00",Cartão de Crédito NUBANK,,Á Vista

In [43]:
for idx, row in df.iterrows():
  
  if row['Valor'].startswith("-") :
     df.drop(idx,axis=0,inplace=True)

  if "." in row['Valor'] :
     df.loc[idx,'Valor'] = row['Valor'].replace(".","")
     

df = df[['Data'] + ['Tipo de Pagamento'] + ['Despesa'] + ['Tipo de Despesa'] + ['Valor'] + ['Pagamento']]

In [45]:
df

,Data,Tipo de Pagamento,Despesa,Tipo de Despesa,Valor,Pagamento
0,2026-06-03,Cartão de Crédito NUBANK,Multsom,,"97,50",Á Vista
1,2026-06-02,Cartão de Crédito NUBANK,Comfrutas Laranja Doce,,"65,62",Á Vista
2,2026-05-28,Cartão de Crédito NUBANK,Ips Br*Onlyfans,,"26,12",Á Vista
3,2026-05-27,Cartão de Crédito NUBANK,Chies Barber,,"70,00",Á Vista
4,2026-05-27,Cartão de Crédito NUBANK,Ebn*Capcut,,"13,00",Á Vista
5,2026-05-26,Cartão de Crédito NUBANK,Amigao Cianorte I,,"60,07",Á Vista
7,2026-05-25,Cartão de Crédito NUBANK,Lovable,,"28,33",Á Vista
8,2026-05-25,Cartão de Crédito NUBANK,"IOF de ""Lovable""",,"0,99",Á Vista
9,2026-05-25,Cartão de Crédito NUBANK,Dl*Google Moises,,"9,99",Á Vista
10,2026-05-23,Cartão de Crédito NUBANK,Ips,,"134,27",Á Vista
11,2026-05-23,Cartão de Crédito NUBANK,Ips Br*Onlyfans,,"52,61",Á Vista
12,2026-05-23,Cartão de Crédito NUBANK,Amazon Br *Amazon,,"41,26",Á Vista
13,2026-05-22,Cartão de Crédito NUBANK,Claude.Ai Subscription,,"113,35",Á Vista
14,2026-05-22,Cartão de Crédito NUBANK,"IOF de ""Claude.Ai Subscription""",,"3,96",Á Vista
16,2026-05-20,Cartão de Crédito NUBANK,Jim.Com* Gabriel Fran,,"1800,00",Á Vista
17,2026-05-16,Cartão de Crédito NUBANK,"IOF de ""Railway""",,"0,91",Á Vista
18,2026-05-16,Cartão de Crédito NUBANK,Comfrutas Laranja Doce,,"144,42",Á Vista
19,2026-05-16,Cartão de Crédito NUBANK,Hk Clinic,,"300,00",Á Vista
20,2026-05-16,Cartão de Crédito NUBANK,Dl*Google Google,,"12,50",Á Vista
21,2026-05-16,Cartão de Crédito NUBANK,Railway,,"26,21",Á Vista
23,2026-05-14,Cartão de Crédito NUBANK,Mp *Gfarma,,"127,42",Á Vista
24,2026-05-14,Cartão de Crédito NUBANK,QMS,,"35,50",Á Vista
25,2026-05-14,Cartão de Crédito NUBANK,Ips Br*Onlyfans,,"17,80",Á Vista
26,2026-05-12,Cartão de Crédito NUBANK,IOF por fatura atrasada,,"7,36",Á Vista
27,2026-05-12,Cartão de Crédito NUBANK,Multa por fatura atrasada,,"37,93",Á Vista
28,2026-05-12,Cartão de Crédito NUBANK,Juros de atraso do Pix no crédito para QMS INT...,,"0,03",Á Vista
29,2026-05-12,Cartão de Crédito NUBANK,Multa de atraso do Pix no crédito para QMS INT...,,"0,39",Á Vista
30,2026-05-12,Cartão de Crédito NUBANK,IOF de atraso do Pix no crédito para QMS INTER...,,"0,00",Á Vista
32,2026-05-11,Cartão de Crédito NUBANK,Pix no Crédito - QMS INTERNACIONAL PROGRAMACAO...,,"21,46",Á Vista
33,2026-05-11,Cartão de Crédito NUBANK,Pix no Crédito - S A RECEBIMENTOS LTDA,,"2,70",Á Vista
34,2026-05-11,Cartão de Crédito NUBANK,Valor pendente do mês anterior,,"1889,36",Á Vista
35,2026-05-11,Cartão de Crédito NUBANK,Pix no Crédito - QMS INTERNACIONAL PROGRAMACAO...,,"22,74",Á Vista
36,2026-05-08,Cartão de Crédito NUBANK,Hk Clinic,,"300,00",Á Vista
37,2026-05-05,Cartão de Crédito NUBANK,Panobiancos Academia -,,"109,90",Á Vista
38,2026-05-04,Cartão de Crédito NUBANK,Aprova Total - Parcela 4/12,,"83,00",Á Vista

In [44]:
valor

'1.800,00'

In [11]:
df = pd.read_csv('NUBANK.csv',encoding='utf-8',sep=',')
df.rename(columns={'title':'Despesa','amount':'Valor','date':'Data'},inplace=True)

df['Tipo de Pagamento'] = 'Cartão de Crédito NUBANK'
df['Tipo de Despesa'] = ''

df['Pagamento'] = 'Á Vista'

for idx, row in df.iterrows():
    if row['Valor'] < 0 :
     df.drop(idx,axis=0,inplace=True)

df = df[['Data'] + ['Tipo de Pagamento'] + ['Despesa'] + ['Tipo de Despesa'] + ['Valor'] + ['Pagamento']]

df['Data'] = pd.to_datetime(df['Data'])

In [14]:
import re
categorias = {
'Alimentação':['comfrutas','amigao','panificadora'],
'Cabelereiro':['chies'],
'Cartão':[],
'Conhecimento':['asimov','unarrado','aprova total','estrategia','livro'],
'Diversos':['google one','notebook'],
'Farmácia':[],
'Igreja':[],
'Música':['música'],
'Plano Celular':['tim'],
'Presentes':[],
'Saúde':['h f','clinica''saúde','saude','treino','coluna','panobiancos'],
'Transporte':['partiu','postos','expresso','uber'],
}

def limpar_texto(texto):
    texto = texto.lower()
    texto = re.sub('[^a-zA-ZÀ-ÿ0-9 ]','',texto)
    texto = texto.strip()
    
    return texto

def mapa_despesas():
   caminho = Path.cwd() / 'csv'
   #data_frames = []

   for csv in caminho.glob('*.csv'):
      map_df = pd.read_csv(csv,encoding='utf-8',sep=',')
    
   return map_df

In [15]:
meses = {
    1:'Janeiro',2:'Fevereiro',3:'Março',4:'Abril',5:'Maio',6:'Junho',
    7:'Julho',8:'Agosto',9:'Setembro',10:'Outubro',11:'Novembro',12:'Dezembro'
    }
df['Ano de Compra'] = df['Data'].dt.year
df['Mês de Compra'] = df['Data'].dt.month.map(meses)

map_df = mapa_despesas()
mapa = {
        limpar_texto(despesa): categoria 
        for despesa, categoria  in (zip(map_df['Despesa'],map_df['Tipo de Despesa']))}
    
def categorizar_despesas(despesa):
        despesa = limpar_texto(despesa)

        if despesa in mapa :
            return mapa[despesa]

        for categoria, tipos in categorias.items():
            for tipo in tipos:
                if tipo in despesa:
                    return categoria
                
        return 'Diversos'

df['Tipo de Despesa'] = df['Despesa'].apply(categorizar_despesas)
df['Valor'] = (df['Valor']
                        .astype(str)
                        .str.replace(',','.',regex=False)
                        .str.strip()
                        .astype(float)
                        )
    
df['Data'] = df['Data'].dt.strftime("%Y-%m-%d")
df.columns = df.columns.str.lower().str.strip()

df = df.rename(columns={'tipo de despesa':'tipo_despesa','tipo de pagamento':'tipo_pagamento','ano de compra':'ano_de_compra','mês de compra':'mês_de_compra'})